In [1]:
import pandas as pd
import numpy as np

In [2]:
#reading in the prepared training data.  currently, data is not scaled.
df = pd.read_excel('data/clean2.xlsx')
df.head()

   age  sex  cp  trestbps  chol  fbs  thalrest  exang  num
0   63    1   1       145   233    1        60      0    0
1   67    1   4       160   286    0        64      1    2
2   67    1   4       120   229    0        78      1    1
3   37    1   3       130   250    0        84      0    0
4   41    0   2       130   204    0        71      0    0

In [3]:
df.loc[df['num'] == 2, 'num'] = 1

In [4]:
df.loc[df['num'] == 3, 'num'] = 2

In [5]:
df.loc[df['num'] == 4, 'num'] = 2

In [6]:
df

     age  sex  cp  trestbps  chol  fbs  thalrest  exang  num
0     63    1   1       145   233    1        60      0    0
1     67    1   4       160   286    0        64      1    1
2     67    1   4       120   229    0        78      1    1
3     37    1   3       130   250    0        84      0    0
4     41    0   2       130   204    0        71      0    0
5     56    1   2       120   236    0        73      0    0
6     62    0   4       140   268    0        83      0    2
7     57    0   4       120   354    0        84      1    0
8     63    1   4       130   254    0        75      0    1
9     53    1   4       140   203    1        86      1    1
10    57    1   4       140   192    0        86      0    0
11    56    0   2       140   294    0        85      0    0
12    56    1   3       130   256    1        74      1    1
13    44    1   2       120   263    0        70      0    0
14    52    1   3       172   199    1        91      0    0
15    57    1   3       150   168    0        60      0    0
16    48    1   2       110   229    0        75      0    1
17    54    1   4       140   239    0        86      0    0
18    48    0   3       130   275    0        62      0    0
19    49    1   2       130   266    0        82      0    0
20    64    1   1       110   211    0        58      1    0
21    58    0   1       150   283    1        75      0    0
22    58    1   2       120   284    0        69      0    1
23    58    1   3       132   224    0        98      0    2
24    60    1   4       130   206    0        83      1    2
25    50    0   3       120   219    0        71      0    0
26    58    0   3       120   340    0        95      0    0
27    66    0   1       150   226    0        49      0    0
28    43    1   4       150   247    0        67      0    0
29    40    1   4       110   167    0        64      1    2
..   ...  ...  ..       ...   ...  ...       ...    ...  ...
868   42    1   4       145   264    0        68      1    1
869   53    1   4       130   264    0        71      1    1
870   55    1   4       140   264    0        53      0    1
871   61    1   4       160   264    1        73      0    1
872   51    1   4       140   264    0        63      0    1
873   70    1   4       115   245    0        65      1    1
874   61    1   4       130   259    0        90      0    2
875   38    1   4       150   245    0        56      1    1
876   57    1   4       160   264    0        57      1    1
877   38    1   4       135   264    0        69      0    1
878   62    0   1       140   264    0        98      0    1
879   58    1   4       170   245    0        66      1    1
880   52    1   4       165   264    0        59      1    1
881   61    1   3       200   259    0        52      0    2
882   50    0   4       160   245    0        74      0    1
883   51    1   4       130   245    0       110      0    1
884   65    1   4       145   259    0        39      0    2
885   52    1   4       135   264    0        70      1    1
886   47    1   3       110   245    0        68      1    1
887   35    1   4       137   259    0        70      1    2
888   57    1   4       140   259    0        78      1    2
889   62    1   4       115   245    0        44      1    1
890   59    1   4       110   259    0        82      0    2
891   53    1   3       160   245    0        91      1    1
892   62    1   4       150   259    0        54      0    2
893   54    1   4       180   245    0        58      0    1
894   56    1   4       125   259    1        55      1    2
895   56    1   3       125   264    0        64      0    1
896   54    1   4       130   259    0        58      1    2
897   66    0   4       155   245    0        66      0    1

[898 rows x 9 columns]

In [7]:
writer = pd.ExcelWriter('binned1.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='numbin1')
writer.save()